### ISSUE TITLE
Request for new contract types: services (support/maintenance/project) and lease (circuits)

### ISSUE THREAD

**Issue by itheodoridis** [nautobot/nautobot-app-device-lifecycle-mgmt#103]
### Environment
* Nautobot version:  1.4.4
* nautobot-plugin-device-lifecycle-mgmt version:  1.0.2

### Proposed Functionality
Add two new contract types:

-  Services : this could be used for support/maintenance/integration type of services.
- Lease: this could be used for circuits that are leased to an enterprise customer by an SP or by an SP leased to a customer/tenant.

### Use Case
Please see above examples.

- For example a contract may cover procurement and limited support of devices. After the first period a new contract could be assigned for extended support of those devices.
- For circuits, a lease contract could be tied to those circuits linking to either Provider or tenant or both.

**Comment by itheodoridis** [comment]
As long as it's supported in general, the additional benefit of it being tied to a circuit is nice to have but not indispensable. 
The service contract however (whatever the sub-type) can absolutely be tied to a device.
I would even go a bit further and offer this remark: The software version (e.g Cisco IOS) can be viewed as an independent object from a device. It has its own lifecycle as it can span multiple devices of different device types. I realize it's not the same as a circuit but just saying..

**Comment by jamestiotio** [comment]
Hi folks, this enhancement request is closed but the merged PR #239 was reverted by #273.

Could I kindly check the following points:

1. Were there any reasons for the revert? Did the initial implementation version cause some bugs?
2. Are there any plans to re-implement this feature?

Thank you!
