### ISSUE TITLE
Associate software to Virtual Machines

### ISSUE THREAD

**Issue by JimmyKip** [nautobot/nautobot-app-device-lifecycle-mgmt#115]
### Environment
* Nautobot version:  1.4.5
* nautobot-plugin-device-lifecycle-mgmt version:  1.0.2

(May be unnecessary depending on if https://github.com/nautobot/nautobot/issues/1178 progresses)

### Proposed Functionality

Have the ability to select Virtual Machines for software relationships, the same as Running on Devices / Running on Inventory Items.

### Use Case

I would like to be able to set software on virtual machines in the same way as is currently available in devices. This would allow for simple tracking of OS on VMs.

Implementing this would also enable Generate Vulnerabilities to highlight CVE that impacts OS running on VMs as well as Devices / Inventory Items.

**Comment by smk4664** [comment]
It looks like [nautobot/nautobot#1178](https://github.com/nautobot/nautobot/issues/1178) is now targeted for 3.0. I believe this will be worth working as part of the migration to Nautobot 2.0.

**Comment by progala** [comment]
Software model is now part of the Nautobot core, so this would have to be implented there. Software model will be removed from DLM starting with version 3.0.
