### ISSUE TITLE
Drift cookie v1

### ISSUE THREAD

**Issue by chadell** [nautobot/nautobot-app-device-lifecycle-mgmt#142]
Update development environment to match the version of 1 of NTC cookiecutter

**Comment by jvanderaa** [comment]
What needs to be done?

**Comment by jvanderaa** [comment]
Not sure that this would be something of a todo out of the 2.0 migration based on the issue title/description applied.

**Comment by chadell** [comment]
Calculate the drift between this plugin development environment and the proposed in the NTC cookie-cutter version 1, and fix the differences.

**Comment by progala** [comment]
@chadell I believe this has been addressed by https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/240 ?
