### ISSUE TITLE
Add `alias` field to Validated Software List CSV Export

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot-app-device-lifecycle-mgmt#152]
### Environment
* Nautobot version:  v1.5.14b1
* nautobot-plugin-device-lifecycle-mgmt version:  v1.1.2

### Proposed Functionality
Presently the CSV export for `Software List` has a column with the alias key, but the `Validated Software List` does not contain this column.

Current columns (and order) for `Software List` export: device_platform,version,alias,release_date,end_of_support,documentation_url,long_term_support,pre_release

Current columns (and order) for `Validated Software List` export: 
software,devices,device_types,device_roles,inventory_items,object_tags,start,end,preferred

Desired columns for `Validated Software List` export: 
software,devices,device_types,device_roles,inventory_items,object_tags,start,end,preferred,alias

### Use Case
As a user I want to export the alias with the "validated software list" CSV export, similar to "software list" CSV export does. This is because the "software" column in the "validated software list" CSV export contains the UUID of the object, which is not very human readable and not obvious which software item it is visually.

**Comment by MeganerdDev** [comment]
https://github.com/nautobot/nautobot-plugin-device-lifecycle-mgmt/pull/153

**Comment by MeganerdDev** [comment]
Also related to the columns exported in “Software” vs “Validated Software”.
I wasn't sure if we should merry up any of these differences as well to make the exports more uniform?


1. version
Exported in “Software” but not “Validated Software” CSV


2. object_tags
Exported in “Validated Software” but not “Software” CSV
Both "Software" and "Validated Software" objects can have tags applied on their respective forms, so maybe export tags and object_tags separately is more appropriate?


3. UUID
This is exported in “Validated Software” CSV as the "software" column
however the “Software” object has a UUID, but it has no equivalent "software" column for its export

**Comment by progala** [comment]
Thanks @MeganerdDev , I agree that it'd be good to revisit exports to make them more useful and consistent.

I think whatever we do we should make sure that the csv files can be used later to recreate objects by using import functionality. That is, I'd be good to test whether we can uniquely match Validated Software to Software objects, without using Software UUID, when importing csv.

2. object_tags on Validated Software are used for dynamically assigning them to groups of devices/inventory items. These are different to standard tags which can be applied to the concrete instances of Software and Validated Software. However, we should porbably add these to the export as well for both models.

**Comment by progala** [comment]
Closing, solution was provided in the linked PR.
