### ISSUE TITLE
Support SMU/Patch concept

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-app-device-lifecycle-mgmt#173]
### Environment
* Nautobot version:  1.5+
* nautobot-plugin-device-lifecycle-mgmt version:  future

### Proposed Functionality
Certain vendor platforms/os support SMUs where you have a base image, then patch updates over time via SMU updates. As an enterprise I would like to track OS version, but also required SMUs to avoid vulnerabilities etc.

### Use Case

Track version, plus all the SMUs required to keep the device/software "safe".

**Comment by jvanderaa** [comment]
Does SMU need to be related to anything? Would this just be another software type on it?

**Comment by progala** [comment]
`Software` model has moved to the Nautobot core so this would have to implemented there.
