### ISSUE TITLE
Job `cve_tracking.py` takes a lot of time to complete

### ISSUE THREAD

**Issue by gertzakis** [nautobot/nautobot-app-device-lifecycle-mgmt#276]
### Environment
* Python version:  3.8.18
* Nautobot version:  1.6.9
* nautobot-device-lifecycle-mgmt version:  1.2.0

### Observed Behavior
If you have a lot of devices, software relationships, etc. the `cve_tracking.py` Job takes a lot of time to complete. In an environment with 150 Softwares, ~550 CVEs and ~24k of devices the Job run for almost 15 hours. 

### Steps to Reproduce
1. Have a lot of data into Nautobot
2. Run `cve_tracking.py` Job

**Comment by bradh11** [comment]
addressed in #275 and #277 & closed in Releases 1.6.0 and 2.1.0
