### ISSUE TITLE
Increase max character limit on SoftwareLCM version field

### ISSUE THREAD

**Issue by housepbass** [nautobot/nautobot-app-device-lifecycle-mgmt#315]
### Environment
* Python version:  3.11
* Nautobot version:  Latest
* nautobot-device-lifecycle-mgmt version:  Latest

### Expected Behavior
When leveraging `napalm`'s `get_facts`, the returned `os_version` value should be usable as the `SoftwareLCM` model version attribute.

### Observed Behavior
For the Cisco ASR platform, the `os_version` characters count (90) returned from `get_facts` exceeds the `SoftwareLCM.version` field's max character limit (50).

### Steps to Reproduce
1. Via ORM, create a new `SoftwareLCM` object with version `ASR1000 Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 17.9.4, RELEASE SOFTWARE (fc5)`
2. Get traceback `psycopg2.errors.StringDataRightTruncation: value too long for type character varying(50)`

**Comment by itdependsnetworks** [comment]
I'm torn on this, on one hand normalizing to 255 here: https://github.com/nautobot/nautobot/pull/5355 on the other hand, this is not the intention of the field.

**Comment by progala** [comment]
`SoftwareLCM` and `SoftwareImageLCM` models are being moved to the Nautobot core, and will be removed from the DLM app in v3.0. Looking at the core PR, the version field will allow up to 255 characters: https://github.com/nautobot/nautobot/pull/5137
