### ISSUE TITLE
Migrations not reversible 

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot-app-device-lifecycle-mgmt#316]
### Environment
* Python version:  3.11
* Nautobot version:  2.1.x
* nautobot-device-lifecycle-mgmt version:  latest

### Expected Behavior
nautobot-server migrate nautobot_device_lifecycle_mgmt zero

### Observed Behavior
Following migrations do not have a reverse_code 

* 0019
* 0017
* 0008

Following tables need to be empty to be able to be reversible
* 0004_squash__0004_0014_0015_0016 - nautobot_device_lifecycle_mgmt_validatedsoftwarelcm 

### Steps to Reproduce
1.
2.
3.

**Comment by whitej6** [comment]
0004_squash__0004_0014_0015_0016 - causes problems on migrate zero, after migrate zero this entry many need to be manually removed.

**Comment by chris-tomkins-flexgrid** [comment]
Also affected by this, I believe - `0019_cve_and_contract_m2m_migration is not reversible when `nautobot-server migrate nautobot_device_lifecycle_mgmt zero`

**Comment by bryanculver** [comment]
We're going to constrain the scope of this story to addressing the missing `reverse_code`. The squash migration will be a separate fix.

**Comment by gsnider2195** [comment]
Fixed by #381
