### ISSUE TITLE
Upstream CI failure with Nautobot 2.2 due to nonstandard `viewsets.py` implementation

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-app-device-lifecycle-mgmt#320]
### Environment
* Python version:  
* Nautobot version:  2.2.0
* nautobot-device-lifecycle-mgmt version:  

### Expected Behavior

Passing upstream CI tests.

### Observed Behavior

Test failure in `nautobot_device_lifecycle_mgmt.tests.test_views.CVELCMViewTest`, likely others will follow.

It appears that the issue is that the Nautobot core API `get_view_for_model()` is unable to locate the `CVELCMUIViewSet` class to inspect it, likely because this class is implemented in `nautobot_device_lifecycle_mgmt.viewsets` module and is not accessible through the expected `nautobot_device_lifecycle_mgmt.views` module.

**Comment by progala** [comment]
Thanks @glennmatthews . As I understand fixing this should be as simple as moving classes from the `viewsets` to `views` module?

**Comment by glennmatthews** [comment]
I believe that to be the case, yes. (Or if you want to keep the separation of files, doing a `from .viewsets import CVELCMUIViewSet, ...` in `views.py` should also suffice)
