### ISSUE TITLE
Release notes missing for > 1.3

### ISSUE THREAD

**Issue by scetron** [nautobot/nautobot-app-device-lifecycle-mgmt#322]
### Environment
* Python version:   3.11
* Nautobot version:   2.
* nautobot-device-lifecycle-mgmt version:  

### Expected Behavior

To see release notes for released versions. 

### Observed Behavior
No release notes mentioned on the docs site.

**Comment by progala** [comment]
Thanks @scetron . We found the issue and we'll get it fixed.

**Comment by progala** [comment]
Release notes added to the docs site.
