### ISSUE TITLE
Disable metrics by default and allow operators to selectively enable metrics of interest.

### ISSUE THREAD

**Issue by progala** [nautobot/nautobot-app-device-lifecycle-mgmt#325]
### Proposed Functionality

Some of the DLM metrics take a lot of time to process for large enough data sets. The proposal is to disable DLM metrics by default and allow operators to specify which metrics to enable via the configuration settings.

**Comment by ubajze** [comment]
If someone else also hits this problem, there is a new feature in the later versions of Nautobot to disable metrics as a workaround.

Add the following environmental variable to the instance: `NAUTOBOT_METRICS_DISABLED_APPS=nautobot_device_lifecycle_mgmt`

**Comment by progala** [comment]
Implemented in next3.0
