### ISSUE TITLE
Increase or standardize max_length on models to 255 characters

### ISSUE THREAD

**Issue by MeganerdDev** [nautobot/nautobot-app-device-lifecycle-mgmt#328]
### Environment
* Nautobot version:  v2.2.2
* nautobot-device-lifecycle-mgmt version:  v2.1.1

### Proposed Functionality
There was previously an effort to standardize the `max_length` on models in Nautobot Core
The proposal is to follow a similar pattern for this App
Alternatively if a standardization for models makes less sense here, an increase of the `max_length` for character fields for some fields may be in order
eg: [support_level](https://github.com/nautobot/nautobot-app-device-lifecycle-mgmt/blob/4059676929dafbf88c9c8341dd3dcb7e395435b7/nautobot_device_lifecycle_mgmt/models.py#L429) max_length is 64, which needs to be increased

Some fields might not be suited for a standardization of 255-character, like [image_file_checksum](https://github.com/nautobot/nautobot-app-device-lifecycle-mgmt/blob/4059676929dafbf88c9c8341dd3dcb7e395435b7/nautobot_device_lifecycle_mgmt/models.py#L223) and can be left as-is

### Related efforts on Nautobot Core
https://github.com/nautobot/nautobot/issues/2906
https://github.com/nautobot/nautobot/pull/5355

**Comment by jvanderaa** [comment]
@MeganerdDev this is only needed on Nautobot 2.x right?
