### ISSUE TITLE
Update the UX for add/edit a Hardware Notice

### ISSUE THREAD

**Issue by joewesch** [nautobot/nautobot-app-device-lifecycle-mgmt#343]
### Environment
* Nautobot version:  2.2.5
* nautobot-device-lifecycle-mgmt version:  2.1.1

### Proposed Functionality
- Add a way to filter the Inventory Part ID list to a specific device or other filterable items (e.g. location)
- Add more information to the label that is shown on each Inventory Part ID option in the dropdown list

### Use Case
When you use the UI to create or edit a Hardware Notice, if you click on the Inventory Part dropdown it shows you every object in the database with just simply the Part ID of the Inventory Item. It's hard to determine which inventory item belongs to which device.

**Comment by joewesch** [comment]
In addition, when opening the form to add a new Hardware Notice, if you have a large number of Inventory Items the form is currently using a `ModelChoiceField` and it is pre-populating the list which can take a long time. We should move this to a dynamic model choice field instead.

**Comment by pszulczewski** [comment]
`inventory_item` field on `HardwareLCM` model is `CharField`, so there is no relation to devices to do filtering.
Reporting is done based on string comparison in this case `part_id` field on `InventoryItem`, each device has information about the hardware notice if there is a match on Inventory Item part ID.

Changing `ModelChoiceField`seems to be a good enough solution.
I have just tested it with 350k inventory items, and it's working fine, I can just use the search box by typing inventory part ID.
350k records with current solution just hangs the browser.
