### ISSUE TITLE
Reports: Remove from reports devices that do not have software

### ISSUE THREAD

**Issue by jvanderaa** [nautobot/nautobot-app-device-lifecycle-mgmt#86]
### Environment
* Nautobot version:  
* nautobot-plugin-device-lifecycle-mgmt version:  

### Proposed Functionality

- Reports - Add in some capability to exclude devices (Such as patch panels)

### Use Case

Hide patch panels and other devices without software from the reporting.

**Comment by progala** [comment]
@jvanderaa Is the proposal to have something different than the existing "Exclude missing software" filter?

![image](https://user-images.githubusercontent.com/27512690/167163142-b6e3ec4e-e31d-412b-976d-2546d9131f6f.png)
