### ISSUE TITLE
Add local upload option to software image.

### ISSUE THREAD

**Issue by jeffkala** [nautobot/nautobot-app-device-lifecycle-mgmt#98]
### Environment
* Nautobot version:  1.2+
* nautobot-plugin-device-lifecycle-mgmt version:  1.0.0

### Proposed Functionality
SoftwareImage should also include a `upload` field.  This should upload the file locally to nautobot for use later.
This could use the django filed `FileField` and the `upload_to` which will save the find to the `MEDIA_ROOT`.

### Use Case
Jim has requirements to use software files that are held by nautobot to upload them to network devices.  This would allow DLM plugin to manange the software, but also provide local file access to be used by jobs etc if it's needed.  It also allows for a option in more secure environments.

**Comment by progala** [comment]
Closing as SoftwareImage model has now been moved to the core.
